# -*- coding: utf-8 -*-
"""Pyspark_basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IFReOAEJ8nbihMAfRSgTXHH0EvvCj2y5
"""

!pip install pyspark

import pyspark

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/apps.csv')

df.head()

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Practise').getOrCreate()

spark

df_pyspark = spark.read.csv('/content/drive/My Drive/Colab Notebooks/apps.csv')

df_pyspark

df_pyspark.show()

df_pyspark=spark.read.option('header','true').csv('/content/drive/My Drive/Colab Notebooks/apps.csv')

type(df_pyspark)

df_pyspark.head(1)

df_pyspark.printSchema